version: "3"
services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    restart: always
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
  
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    command: ["flask", "run", "--host=0.0.0.0", "--port=5001", "--debugger"]
    restart: always
    volumes:
      - ./api:/api:cached
      - ./results:/results
      - ./public:/public
    depends_on:
      - redis
      - nginx-proxy
    ports:
      - "5001:5001"
    environment:
      VIRTUAL_HOST: localhost
      VIRTUAL_PORT: 5001
      API_ENVIRONMENT: development
  
  worker:
    build:
      context: celery-queue
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - redis
      - nginx-proxy
    volumes:
      - ./results:/results
      - ./public:/public
  
  worker-monitor:
    build:
      context: celery-queue
      dockerfile: Dockerfile
    restart: always
    entrypoint: flower
    command: -A tasks --port=5555 --broker=redis://redis:6379/0
    depends_on:
      - redis
      - nginx-proxy
    environment:
      VIRTUAL_HOST: localhost
      VIRTUAL_PORT: 5555
  
  cogeto-client:
    build:
      context: ./cogeto-client
      dockerfile: Dockerfile.local
    restart: always
    environment:
      VIRTUAL_HOST: localhost
      VIRTUAL_PORT: 80
    depends_on:
      - nginx-proxy
  
  # Development setup for metrical-tree-client with hot reloading
  metrical-tree-client:
    build:
      context: ./metrical-tree-client
      dockerfile: Dockerfile.dev
    user: "${UID:-1000}:${GID:-1000}"
    volumes:
      - ./metrical-tree-client:/app:cached
      - /app/node_modules
      - metrical-tree-client-node-modules:/app/node_modules/.cache
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
      - VIRTUAL_HOST=metricaltree.local
      - VIRTUAL_PORT=3000
      - REACT_APP_API_URL=http://localhost:5001
      - WDS_SOCKET_HOST=localhost
      - WDS_SOCKET_PORT=3000
      - WDS_SOCKET_PATH=/ws
      - DANGEROUSLY_DISABLE_HOST_CHECK=true
      - PUBLIC_URL=http://localhost:3000
      - NODE_ENV=development
    networks:
      - default
    depends_on:
      - nginx-proxy
  
  redis:
    image: redis
    restart: always

networks:
  default:

volumes:
  metrical-tree-client-node-modules:
