version: "3"
services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    restart: always
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - /apps/docker-articles/nginx/vhost.d:/etc/nginx/vhost.d
      - /apps/docker-articles/nginx/certs:/etc/nginx/certs:ro
      - /apps/docker-articles/nginx/html:/usr/share/nginx/html
    labels:
      com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy: "true"
  letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /apps/docker-articles/nginx/vhost.d:/etc/nginx/vhost.d
      - /apps/docker-articles/nginx/certs:/etc/nginx/certs:rw
      - /apps/docker-articles/nginx/html:/usr/share/nginx/html
    depends_on:
      - nginx-proxy
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    restart: always
    volumes:
      - ./results:/results
      - ./public:/public
    depends_on:
      - redis
      - nginx-proxy
    environment:
      VIRTUAL_HOST: cogeto-api.stanford.edu
      VIRTUAL_PORT: 5001
      LETSENCRYPT_HOST: cogeto-api.stanford.edu
      LETSENCRYPT_EMAIL: jsolis@graycoltdevelopers.com
      API_ENVIRONMENT: production
  worker:
    build:
      context: celery-queue
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - redis
      - nginx-proxy
    volumes:
      - ./results:/results
      - ./public:/public
  worker-monitor:
    build:
      context: celery-queue
      dockerfile: Dockerfile
    restart: always
    entrypoint: flower
    command: -A tasks --port=5555 --broker=redis://redis:6379/0
    depends_on:
      - redis
      - nginx-proxy
    environment:
      VIRTUAL_HOST: cogeto-monitor.stanford.edu
      VIRTUAL_PORT: 5555
      LETSENCRYPT_HOST: cogeto-monitor.stanford.edu
      LETSENCRYPT_EMAIL: jsolis@graycoltdevelopers.com
  cogeto-client:
    build:
      context: ./cogeto-client
      dockerfile: Dockerfile
    restart: always
    environment:
      VIRTUAL_HOST: cogeto.stanford.edu
      VIRTUAL_PORT: 80
      LETSENCRYPT_HOST: cogeto.stanford.edu
      LETSENCRYPT_EMAIL: jsolis@graycoltdevelopers.com
    depends_on:
      - nginx-proxy
  metrical-tree-client:
    build:
      context: ./metrical-tree-client
      dockerfile: Dockerfile
    restart: always
    environment:
      VIRTUAL_HOST: metricaltree.stanford.edu
      VIRTUAL_PORT: 80
      LETSENCRYPT_HOST: metricaltree.stanford.edu
      LETSENCRYPT_EMAIL: jsolis@graycoltdevelopers.com
    depends_on:
      - nginx-proxy
  redis:
    image: redis:7.0.10
    restart: always
    command: ["redis-server", "--appendonly", "yes", "--appendfsync", "everysec"]
    volumes:
      - redis-data:/data
    ports:
      - "127.0.0.1:6379:6379"

volumes:
  redis-data:
    driver: local